In [5]:
from dataset_ihdp import *

In [6]:
data = load(data_path  = Path.cwd())

/home/nvth2/meta-CATE/cate/CATENets/catenets/datasets/ihdp_npci_1-100.train.npz


In [7]:
data_train, data_test = load_raw(data_path  = Path.cwd())

/home/nvth2/meta-CATE/cate/CATENets/catenets/datasets/ihdp_npci_1-100.train.npz


In [8]:
X,w,y, a,b,c = data

In [9]:
w

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],

In [26]:
a.shape

(672, 2)

In [28]:
b.shape

(75, 25)

In [30]:
c

array([[6.40771851, 7.52770334],
       [1.37564771, 5.98912474],
       [2.13758965, 6.42987892],
       [2.26805964, 6.48912474],
       [3.42142096, 6.90025601],
       [1.85225184, 6.28660217],
       [2.75627337, 6.6840796 ],
       [1.47781266, 6.06076312],
       [2.53145609, 6.59899472],
       [1.63117689, 6.15950183],
       [2.11466115, 6.41909465],
       [3.36227642, 6.88281831],
       [1.80045694, 6.25824055],
       [2.69368475, 6.66111011],
       [2.79769165, 6.69899472],
       [1.51840949, 6.08786346],
       [3.50533721, 6.92448678],
       [2.70483497, 6.66524096],
       [2.18725722, 6.45284841],
       [0.9244533 , 5.59164732],
       [1.9341711 , 6.32987892],
       [1.97911218, 6.35284841],
       [1.42108002, 6.02161722],
       [4.694408  , 7.21657207],
       [2.85089591, 6.71783336],
       [3.84830696, 7.01783336],
       [2.58611273, 6.62035593],
       [4.75294567, 7.22896463],
       [1.33718019, 5.96076312],
       [3.36227642, 6.88281831],
       [1.

In [17]:
X = np.array(X)

In [19]:
X.shape

(672, 25)

In [21]:
w.shape

(672, 1)

In [23]:
y

array([[ 1.93856829],
       [ 3.89968653],
       [ 2.40589425],
       [ 1.46932746],
       [ 0.5587762 ],
       [ 1.59723816],
       [ 6.93299396],
       [ 1.3073494 ],
       [ 1.65282508],
       [ 2.56357658],
       [ 2.22342782],
       [ 6.88671946],
       [ 0.49974081],
       [ 6.473671  ],
       [ 2.48508732],
       [ 2.33110502],
       [ 5.59991629],
       [ 0.49340998],
       [ 1.44741284],
       [-0.83245679],
       [ 4.30837631],
       [ 3.21540202],
       [ 2.05560967],
       [ 2.70439652],
       [ 3.51103681],
       [ 4.10923926],
       [ 1.45536116],
       [ 1.62211406],
       [ 2.31262679],
       [ 1.79799718],
       [-0.0296184 ],
       [ 1.88496556],
       [ 1.57041688],
       [ 2.80194023],
       [ 5.54891614],
       [11.26822777],
       [ 3.44250009],
       [ 2.13134649],
       [ 5.68588522],
       [ 1.83024091],
       [ 2.00903424],
       [ 4.50569977],
       [ 7.17012592],
       [ 7.63018615],
       [ 1.60438961],
       [ 9